routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('customers',CustomersController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/customers.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class customers extends Model
{
    use HasFactory;
    protected $table = 'customer';
    public $primarykey = 'id';
    public $timestamps = false;
    public function getgioitinhAttribute(){
        if($this->gender == 1){
            return 'Nam';
        }else{
            return 'Nữ';
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\customers;
use Illuminate\Support\Facades\Redirect;
class CustomersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $listCustomer = customers::where('full_name', 'like', "%$search%")
            ->orwhere('phone', 'like', "%$search%")->paginate(10);
        return view(
            'customers.index',
            compact($listCustomer),
            [
                "listCustomer" => $listCustomer,
                "search" => $search
            ]
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'full_name' => 'required',
            'phone' => 'required',
            'email' => 'required|unique:customer',
            'image' => 'required'
        ], [
            'email.required' => "Email không được để trống",
            'email.unique' => "Email đã tồn tại",
            'phone.required' => "Số điện thoại không được để trống",
            'image.required' => "Ảnh chưa có mục được chọn",
            'full_name.required' => "Họ tên không được để trống",
        ]);

        $image = $request->file('image');
        $newImageName = time() . '.' . $image->getClientOriginalExtension();
        $request->image->move(public_path('images'), $newImageName);
        $full_name = $request->get('full_name');
        $email = $request->get('email');
        $gender = $request->get('gender');
        $phone = $request->get('phone');
        $customer = new customers();
        $customer->full_name = $full_name;
        $customer->email = $email;
        $customer->phone = $phone;
        $customer->gender = $gender;
        $customer->image = $newImageName;
        $customer->save();
        return Redirect::route('customers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customers/create.blade.php
@extends('layout.app')
@section('content')
<h1 align="center">Thêm khách hàng</h1>
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>
        <div class="col-3"></div>
    </div>
</div>

<form action="{{route('customers.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <table border="1" align="center">
        <tr>
            <td>
                Họ và tên <input type="text" name="full_name">
            </td>
        </tr>
        <tr>
            <td>
                Email <input type="text" name="email">
            </td>
        </tr>
        <tr>
            <td>
                Giới tính <input type="radio" name="gender" value="1" checked> nam
                <input type="radio" name="gender" value="0"> nữ
            </td>
        </tr>
        <tr>
            <td>
                Số điện thoại <input type="text" name="phone">
            </td>
        </tr>
        <tr>
            <td>
                Ảnh đại diện <input type="file" name="image">
            </td>
        </tr>
        <tr>
            <td>
                <button>thêm</button>
            </td>
        </tr>
    </table>
</form>
@endsection

resources/views/customers/index.blade.php
@extends('layout.app')
@section('content')
<h1 align="center">Danh sách khách hàng</h1>
<a href="{{route('customers.create')}}">Thêm khách hàng</a>
<form action="" method="get">
    <input type="text" name="search" value="{{$search}}">
    <button class="btn btn-info">
        search
    </button>


</form>
<div class="table-responsive">
    <table border="1" width="50%" class="table">
        <tr>
            <th>
                Họ và tên
            </th>
            <th>
                Email
            </th>
            <th>
                Giới tính
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Ảnh đại diện
            </th>
        </tr>
        @foreach($listCustomer as $customer)
        <tr>
            <td>
                {{$customer->full_name}}
            </td>
            <td>
                {{$customer->email}}
            </td>
            <td>
                {{$customer->gioitinh}}
            </td>
            <td>
                {{$customer->phone}}
            </td>
            <td width="20%">
                <img src="{{ asset('images/' . $customer->image) }}" width="100px" height="110px">
            </td>

        </tr>
        @endforeach
    </table>
</div>
@endsection

resources/views/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/css/app.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>

<body>

    <body>
        @yield('content')

        <script src="/js/app.js"></script>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    </body>
</body>

</html>